const tasks = [
  {phase:"Orientation",title:"Review the campus assurance pilot",short:"Pilot brief",body:`
    <p class="lead">PetroVale has completed the DC1 ACI pilot. Management now wants operational evidence from Cisco Catalyst Center before considering any campus transformation.</p>
    <div class="role-banner"><strong>Your role</strong><p>You are the SDN Network Architect in PetroVale's IT team. Use the instructor-provided Catalyst Center instance and sample data to evaluate assurance and troubleshooting for the existing campus.</p></div>
    <img class="topology" src="assets/brownfield-campus-assurance.svg" alt="Traditional two-building campus observed by Catalyst Center assurance">
    <article class="stakeholder-record"><div class="record-type">Executive pilot authorization</div><dl><dt>From</dt><dd>Nguyễn Minh Quân, CIO</dd><dt>To</dt><dd>Campus Operations; SDN Network Architect</dd><dt>CC</dt><dd>CISO; Infrastructure Director; Service Desk</dd><dt>Subject</dt><dd>Assurance first, architecture change later</dd></dl><p>Dear colleagues, good morning.</p><p>The ACI implementation demonstrated the value of centralized visibility and policy operations in the data center. For the campus, management is authorizing an assurance pilot only. We need to understand whether Catalyst Center improves incident detection, client support, and operational evidence before we discuss SDA.</p><p>Please evaluate the provided wired and wireless data without provisioning devices, changing templates, creating a fabric site, or modifying production policy. The outcome must distinguish what Catalyst Center observed from what it inferred and what the team independently validated.</p><p class="record-signature">Regards,<br>Nguyễn Minh Quân<br>Chief Information Officer<br>PetroVale Energy</p></article>
    <section class="warning"><strong>Hard boundary</strong><p>Do not use Design or Provision workflows to change the campus. Do not create an SDA fabric, VN, SGT policy, LAN automation job, template deployment, software-image update, packet capture, or issue resolution action unless the instructor explicitly releases it.</p></section>
    <h3>Completion evidence</h3><ul><li>Site and inventory scope</li><li>Overall, network-device, wired-client, and wireless-client health baselines</li><li>Device 360 and Client 360 evidence</li><li>Issue, event, path, RF, onboarding, and trend correlation</li><li>Incident records, RCA, dashboard design, and operating recommendations</li></ul>
    <section class="references"><h3>Cisco references</h3><p><a href="https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/catalyst-center-assurance/3-1-x/b_cisco_catalyst_assurance_3_1_x_ug/b_cisco_catalyst_assurance_3_1_x_ug_chapter_0101.html" target="_blank" rel="noreferrer">Overall Enterprise Health</a> · <a href="https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/catalyst-center-assurance/2-3-7/b_cisco_catalyst_assurance_2_3_7_ug.pdf" target="_blank" rel="noreferrer">Catalyst Assurance User Guide</a></p></section>`},

  {phase:"Access and scope",title:"Sign in and establish the evidence window",short:"Access and scope",body:`
    <p class="lead">Record the release, role, accessible sites, sample-data time range, and feature availability before interpreting any health result.</p>
    <div class="worksheet"><label>Catalyst Center release<input data-field="release" placeholder="Read from About"></label><label>Assigned role / site scope<input data-field="role" placeholder="Provided by instructor"></label><label>Sample-data start and end<input data-field="timeWindow" placeholder="Exact time zone"></label><label>Campus site hierarchy<input data-field="siteScope" placeholder="Area / building / floor"></label></div>
    <div class="gui-path"><strong>Start</strong><code>Catalyst Center sign-in · About · user profile · Assurance</code></div>
    <ol class="steps"><li>Sign in using the instructor credentials. Do not enter the password in this page.</li><li>Open the user or help menu and record the Catalyst Center release. Menu labels vary by release; use the equivalent Assurance dashboard path shown by the instructor.</li><li>Confirm your role is restricted to the pilot sites and read-only or assurance operations. Record any dashboards hidden by site-based RBAC.</li><li>Set the global time range to the sample-data window. Record the displayed time zone; do not compare events from different time zones without conversion.</li><li>Open <strong>Assurance &gt; Health</strong> or the release-equivalent dashboard. Confirm data is present before beginning.</li></ol>
    <div class="verify"><strong>Checkpoint</strong><p>The release, role, site scope, time zone, evidence window, and unavailable features are documented.</p></div>`},

  {phase:"Inventory context",title:"Map sites, inventory, and brownfield roles",short:"Inventory",body:`
    <p class="lead">Assurance is meaningful only when device identity, site assignment, role, and telemetry state are correct.</p>
    <div class="gui-path"><strong>Explore</strong><code>Design &gt; Network Hierarchy · Provision &gt; Inventory · Topology</code></div>
    <ol class="steps"><li>Open the site hierarchy without editing it. Identify Building 1, Building 2, floors, and any unassigned devices.</li><li>Open Inventory. Filter the pilot sites and record counts for routers, core/distribution/access switches, wireless controllers, and access points.</li><li>For each device class, review reachability, manageability, collection status, software version, site, role, and last synchronization time.</li><li>Compare the inventory roles with the brownfield diagram. Note any access switch classified as distribution, device assigned to the wrong site, duplicate device, or unmanaged component.</li><li>Open Topology and verify that links represent the expected OSPF, EIGRP, trunk, WLC, and AP relationships. A missing link is evidence to investigate, not proof that the physical link is down.</li></ol>
    <table class="check-table"><thead><tr><th>Object</th><th>Expected role</th><th>Observed role/site</th><th>Data quality concern</th></tr></thead><tbody><tr><td>Building 1 cores</td><td>Core</td><td><input data-field="invCore"></td><td><input data-field="invCoreConcern"></td></tr><tr><td>Building 2 distribution</td><td>Distribution</td><td><input data-field="invDist"></td><td><input data-field="invDistConcern"></td></tr><tr><td>Catalyst 9800</td><td>Wireless controller</td><td><input data-field="invWlc"></td><td><input data-field="invWlcConcern"></td></tr></tbody></table>`},

  {phase:"Operational baseline",title:"Build the campus assurance baseline",short:"Health baseline",body:`
    <p class="lead">Capture normal counts, health distribution, trends, and known exclusions before opening an incident.</p>
    <div class="gui-path"><strong>Explore</strong><code>Assurance &gt; Health &gt; Overall · Network · Client</code></div>
    <ol class="steps"><li>On Overall Health, record network-device, wired-client, and wireless-client health for the same five-minute point and broader trend window.</li><li>Drill from the enterprise view to each building and floor. Identify whether a poor score is broad, site-specific, device-specific, or client-specific.</li><li>Record good, fair, poor, inactive, and onboarding-failure populations. Do not mix inactive clients with failed clients.</li><li>Review the issues contributing to each score. Distinguish score-impacting issues from informational events.</li><li>Compare current values with the available trend or learned baseline. Record data gaps, maintenance-mode exclusions, and devices not contributing to health.</li></ol>
    <div class="worksheet"><label>Network health baseline<textarea data-field="baseNetwork"></textarea></label><label>Wired client baseline<textarea data-field="baseWired"></textarea></label><label>Wireless client baseline<textarea data-field="baseWireless"></textarea></label><label>Known data limitations<textarea data-field="baseLimits"></textarea></label></div>
    <div class="notice"><strong>Interpretation</strong><p>A green aggregate score does not prove every application or client path is healthy. Preserve the denominator, time range, site filter, excluded entities, and contributing KPIs with every screenshot.</p></div>`},

  {phase:"Wired operations",title:"Use Device 360 to investigate a campus switch",short:"Device 360",body:`
    <p class="lead">Follow a poor or instructor-selected switch from the network dashboard into Device 360 and correlate health, interfaces, neighbors, CPU, memory, and issues.</p>
    <div class="worksheet"><label>Selected device<input data-field="deviceName"></label><label>Site / role<input data-field="deviceSite"></label><label>Incident time<input data-field="deviceTime"></label><label>Primary symptom<input data-field="deviceSymptom"></label></div>
    <ol class="steps"><li>From Network Health, select the assigned device or search for its name, management IP, or serial number.</li><li>Open Device 360 and align its timeline with the incident window.</li><li>Review summary health, reachability, last update, software, uptime, and open issues.</li><li>Inspect interface utilization, errors, discards, duplex, speed, PoE, and neighbor information. Compare the affected port with an equivalent healthy port.</li><li>Review CPU, memory, environmental, and link trends. Correlate any change with events or topology changes.</li><li>Record the affected object, evidence, and next validation. Do not conclude root cause from a single red KPI.</li></ol>
    <div class="evidence-pack"><strong>Evidence statement</strong><p>Write one sentence each for intended state, Catalyst Center observation, device evidence available in Device 360, and remaining uncertainty.</p><textarea data-field="deviceEvidence"></textarea></div>`},

  {phase:"Wired client incident",title:"Troubleshoot a wired client onboarding failure",short:"Wired Client 360",body:`
    <div class="incident-banner"><strong>INC-2041 · Building 2 engineering workstation cannot join the network</strong><span class="severity">Priority 2</span></div>
    <article class="stakeholder-record"><div class="record-type">Service desk escalation</div><dl><dt>From</dt><dd>Phạm Thùy Linh, Service Desk Lead</dd><dt>To</dt><dd>Campus Operations</dd><dt>CC</dt><dd>Security Operations; SDN Network Architect</dd><dt>Subject</dt><dd>User moved desks and now receives no usable address</dd></dl><p>Dear team, good afternoon.</p><p>The user was working in Building 1 yesterday and moved to Building 2 this morning. Link is present, but the workstation cannot reach internal services. The desktop team has already replaced the cable.</p><p>Please determine whether the failure is switch access, authentication, address assignment, or an upstream path issue. We need evidence before another port or VLAN change is requested.</p><p class="record-signature">Thanks,<br>Phạm Thùy Linh<br>Service Desk Lead</p></article>
    <div class="gui-path"><strong>Explore</strong><code>Assurance &gt; Health &gt; Client · search MAC/IP/user · Client 360</code></div>
    <ol class="steps"><li>Search the assigned wired-client MAC, IP, or username and open Client 360.</li><li>Set the incident time range. Review connection state, switch, port, VLAN, IP, user, site, and health timeline.</li><li>Open Onboarding and inspect the event sequence. Separate link, 802.1X/MAB, AAA, DHCP, and DNS evidence.</li><li>Compare the current session with the client's last healthy session in Building 1. Identify which stage first diverges.</li><li>Open the attached switch and port in Device 360. Check errors, access mode, operational VLAN, and related issues.</li><li>Classify the most defensible fault domain and identify the team that owns the next validation.</li></ol>
    <table class="check-table"><thead><tr><th>Candidate</th><th>Supporting evidence</th><th>Contradicting evidence</th><th>Status</th></tr></thead><tbody><tr><td>Physical/access port</td><td><input data-field="wiredPhysicalPro"></td><td><input data-field="wiredPhysicalCon"></td><td><select data-field="wiredPhysical"><option>Open</option><option>Supported</option><option>Rejected</option></select></td></tr><tr><td>AAA/identity</td><td><input data-field="wiredAaaPro"></td><td><input data-field="wiredAaaCon"></td><td><select data-field="wiredAaa"><option>Open</option><option>Supported</option><option>Rejected</option></select></td></tr><tr><td>DHCP/addressing</td><td><input data-field="wiredDhcpPro"></td><td><input data-field="wiredDhcpCon"></td><td><select data-field="wiredDhcp"><option>Open</option><option>Supported</option><option>Rejected</option></select></td></tr></tbody></table>`},

  {phase:"Path assurance",title:"Run and interpret Path Trace",short:"Path Trace",body:`
    <p class="lead">Use Path Trace to visualize the known path, then identify what the result does and does not prove in this traditional campus.</p>
    <div class="worksheet"><label>Source client / IP<input data-field="pathSource"></label><label>Destination IP<input data-field="pathDestination"></label><label>Protocol / port<input data-field="pathProtocol"></label><label>Trace timestamp<input data-field="pathTime"></label></div>
    <ol class="steps"><li>From Client 360, choose <strong>Run New Path Trace</strong>, or open the release-equivalent Path Trace tool.</li><li>Enter the instructor-provided source and destination. Add protocol and port only when supported by the instance.</li><li>Run the trace without changing the network. Record discovered devices, interfaces, switched/routed indications, ECMP information, and incomplete segments.</li><li>Compare the displayed path with the brownfield topology, including the Building 1 EIGRP/OSPF redistribution point.</li><li>Identify components outside visibility, such as an unmanaged hop, firewall, server stack, or application process.</li><li>State whether the trace proves topology, policy, forwarding, reachability, or only part of those claims.</li></ol>
    <div class="warning"><strong>Do not overclaim</strong><p>An incomplete trace does not by itself prove packet loss. A complete topology trace does not prove that the application transaction succeeded.</p></div>`},

  {phase:"Wireless baseline",title:"Explore wireless health, floors, APs, and RF",short:"Wireless health",body:`
    <p class="lead">Move from enterprise wireless health to site, floor, WLC, AP, radio, SSID, and client evidence.</p>
    <div class="gui-path"><strong>Explore</strong><code>Assurance &gt; Health &gt; Network/Client · wireless filters · WLC 360 · AP 360 · floor map</code></div>
    <ol class="steps"><li>Filter Network Health to wireless controllers and APs. Record healthy and unhealthy counts by building and floor.</li><li>Open the Catalyst 9800 controller view. Review reachability, AP count, client count, software, interfaces, issues, and trends.</li><li>Open the assigned AP 360. Record operational state, controller, site, radios, channel, channel width, transmit power, client count, utilization, noise, and interference where available.</li><li>Open the floor map. Compare AP placement and client distribution with the AP's assigned site.</li><li>Review SSID and wireless-client health. Separate onboarding failures from poor connected-client experience.</li><li>Record whether sample-data limitations prevent RF, floor, or Intelligent Capture conclusions.</li></ol>
    <div class="worksheet"><label>WLC and AP baseline<textarea data-field="wirelessDeviceBase"></textarea></label><label>RF and floor baseline<textarea data-field="wirelessRfBase"></textarea></label><label>SSID/client baseline<textarea data-field="wirelessClientBase"></textarea></label><label>Visibility limitations<textarea data-field="wirelessLimits"></textarea></label></div>`},

  {phase:"Wireless client incident",title:"Troubleshoot a wireless roaming complaint",short:"Wireless Client 360",body:`
    <div class="incident-banner"><strong>INC-2057 · Voice client experiences interruption between Building 2 floors</strong><span class="severity">Priority 2</span></div>
    <article class="stakeholder-record"><div class="record-type">Unified communications escalation</div><dl><dt>From</dt><dd>Vũ Hoàng Nam, Collaboration Lead</dd><dt>To</dt><dd>Wireless Operations</dd><dt>CC</dt><dd>Service Desk; SDN Network Architect</dd><dt>Subject</dt><dd>Determine whether roaming or application quality caused the call interruption</dd></dl><p>Dear team, good morning.</p><p>A user reports a brief call interruption while moving between floors. The device remained associated to CORP-WIFI, and the overall wireless health dashboard was green when the ticket was opened.</p><p>Please use the historical session and roaming evidence. We need to know whether the interruption correlates with RF conditions, roam duration, authentication, controller events, or an application path outside wireless assurance.</p><p class="record-signature">Regards,<br>Vũ Hoàng Nam<br>Collaboration Lead</p></article>
    <ol class="steps"><li>Search the assigned wireless-client MAC or user and open Client 360.</li><li>Set the timeline around the reported movement. Record SSID, AP, band, channel, RSSI, SNR, data rate, health, and controller.</li><li>Review connectivity and roaming events. Identify the source AP, target AP, roam type, duration, and failure or delay reason where present.</li><li>Compare client RF metrics before, during, and after the event with AP 360 utilization, interference, and radio changes.</li><li>Review onboarding and AAA events to determine whether reauthentication contributed.</li><li>Review application experience only if the sample instance contains it. Keep call signaling/media evidence separate from RF inference.</li><li>If Intelligent Capture data already exists, inspect it. Do not start a new capture without instructor approval.</li></ol>
    <div class="evidence-pack"><strong>Incident conclusion</strong><textarea data-field="wirelessConclusion" placeholder="Evidence, likely fault domain, remaining uncertainty, next owner"></textarea></div>`},

  {phase:"Issue operations",title:"Correlate issues, events, and suggested actions",short:"Issues and events",body:`
    <p class="lead">Treat an issue as a correlated hypothesis with lifecycle state, not as self-proving root cause.</p>
    <div class="gui-path"><strong>Explore</strong><code>Assurance &gt; Issues and Events · Issues · Events · trends</code></div>
    <ol class="steps"><li>Filter issues to the pilot site and incident window. Record severity, category, first occurrence, last occurrence, affected entities, and status.</li><li>Open one wired and one wireless issue. Review the description, supporting events, suggested actions, and affected site/device/client.</li><li>Compare issue timing with Device 360 or Client 360. Determine whether the issue preceded, followed, or merely overlapped the user symptom.</li><li>Review recurring and transient behavior. Identify duplicate symptoms that may share a parent device or service.</li><li>Do not mark an issue resolved or ignored. Record what evidence would be required to change lifecycle state.</li></ol>
    <table class="check-table"><thead><tr><th>Issue</th><th>Catalyst Center hypothesis</th><th>Independent evidence</th><th>Operational action</th></tr></thead><tbody><tr><td><input data-field="issue1"></td><td><input data-field="hypothesis1"></td><td><input data-field="independent1"></td><td><input data-field="action1"></td></tr><tr><td><input data-field="issue2"></td><td><input data-field="hypothesis2"></td><td><input data-field="independent2"></td><td><input data-field="action2"></td></tr></tbody></table>`},

  {phase:"Device incident",title:"Investigate a distribution-path degradation",short:"Device incident",body:`
    <div class="incident-banner"><strong>INC-2072 · Building 2 clients report intermittent slowness</strong><span class="severity">Priority 1</span></div>
    <p>The aggregate client score fell only slightly, but issue correlation points to a Building 2 distribution device during the same period.</p>
    <ol class="steps"><li>Start at the site health trend, not the current snapshot. Identify the first affected KPI and time.</li><li>Drill into the distribution pair and access switches. Compare health, interfaces, errors, discards, utilization, CPU, memory, and neighbor changes.</li><li>Review topology for link-state or STP changes. Correlate with events rather than assuming every missing link is physical failure.</li><li>Compare affected and unaffected clients by access switch, VLAN, floor, and path.</li><li>Run an instructor-provided Path Trace for one affected and one healthy client to the same destination.</li><li>Decide whether evidence favors access, distribution, routing redistribution, upstream application, or insufficient telemetry.</li></ol>
    <div class="worksheet"><label>Blast radius<textarea data-field="blastRadius"></textarea></label><label>First abnormal signal<textarea data-field="firstSignal"></textarea></label><label>Most likely domain<textarea data-field="likelyDomain"></textarea></label><label>Validation required<textarea data-field="requiredValidation"></textarea></label></div>`},

  {phase:"Data quality",title:"Test assurance blind spots and telemetry readiness",short:"Data quality",body:`
    <p class="lead">Determine when missing or stale data is the problem rather than the network itself.</p>
    <ol class="steps"><li>Identify inventory entries that are unreachable, partial collection, unsynchronized, unmanaged, or assigned to the wrong site.</li><li>Check whether wired endpoint data collection is represented for the selected site. Clients on trunks or port channels may not appear as ordinary wired clients.</li><li>Check whether the WLC was discovered by management IP and whether wireless telemetry is available for WLC, AP, and client views.</li><li>Compare device time and Catalyst Center time. Record any NTP or sample-window mismatch.</li><li>Identify unsupported or unavailable features such as Application Experience, Intelligent Capture, floor maps, ISE detail, or historical depth.</li><li>Create a readiness gap for every missing data source rather than labeling the entity healthy.</li></ol>
    <table class="check-table"><thead><tr><th>Required evidence</th><th>Available?</th><th>Gap effect</th><th>Remediation owner</th></tr></thead><tbody><tr><td>Wired endpoint telemetry</td><td><select data-field="gapWired"><option>Unknown</option><option>Yes</option><option>No</option></select></td><td><input data-field="gapWiredEffect"></td><td><input data-field="gapWiredOwner"></td></tr><tr><td>Wireless telemetry</td><td><select data-field="gapWireless"><option>Unknown</option><option>Yes</option><option>No</option></select></td><td><input data-field="gapWirelessEffect"></td><td><input data-field="gapWirelessOwner"></td></tr><tr><td>ISE/AAA detail</td><td><select data-field="gapAaa"><option>Unknown</option><option>Yes</option><option>No</option></select></td><td><input data-field="gapAaaEffect"></td><td><input data-field="gapAaaOwner"></td></tr></tbody></table>`},

  {phase:"Operational design",title:"Design dashboards, alerts, and escalation",short:"Dashboard design",body:`
    <p class="lead">Turn the exploration into a role-based operating model for NOC, wireless, service desk, and management.</p>
    <ol class="steps"><li>Define the NOC first screen: site health trend, critical issues, unreachable infrastructure, client onboarding failures, and top affected sites.</li><li>Define the service desk view: client search, current attachment, onboarding stage, recent events, issue status, and escalation evidence.</li><li>Define the wireless view: WLC/AP health, AP availability, onboarding failures, RF utilization/interference, roaming, and affected SSIDs.</li><li>Choose thresholds and persistence windows that reduce transient noise without hiding real user impact.</li><li>For every alert, define owner, severity, deduplication key, required evidence, escalation trigger, and closure test.</li></ol>
    <table class="check-table"><thead><tr><th>Signal</th><th>Audience</th><th>Trigger/persistence</th><th>Required response</th></tr></thead><tbody><tr><td><input data-field="signal1"></td><td><input data-field="audience1"></td><td><input data-field="trigger1"></td><td><input data-field="response1"></td></tr><tr><td><input data-field="signal2"></td><td><input data-field="audience2"></td><td><input data-field="trigger2"></td><td><input data-field="response2"></td></tr><tr><td><input data-field="signal3"></td><td><input data-field="audience3"></td><td><input data-field="trigger3"></td><td><input data-field="response3"></td></tr></tbody></table>`},

  {phase:"Incident management",title:"Build the incident timeline and RCA",short:"RCA",body:`
    <p class="lead">Use one wired or wireless incident to produce an evidence-based timeline, restoration test, and corrective-action plan.</p>
    <ol class="steps"><li>Record detection time, user report, first Catalyst Center signal, triage start, evidence milestones, escalation, restoration, and validation.</li><li>Separate symptom, impact, trigger, contributing factors, and root cause. Do not restate a health score as root cause.</li><li>Identify why monitoring did or did not detect the issue before the user.</li><li>Document the restoration test from the user's perspective and the network evidence that supports it.</li><li>Create corrective actions for technology, telemetry, process, ownership, and runbook gaps.</li></ol>
    <div class="worksheet"><label>Impact and duration<textarea data-field="rcaImpact"></textarea></label><label>Technical timeline<textarea data-field="rcaTimeline"></textarea></label><label>Root cause and contributors<textarea data-field="rcaCause"></textarea></label><label>Corrective actions<textarea data-field="rcaActions"></textarea></label></div>
    <div class="verify"><strong>RCA quality gate</strong><p>Another engineer should be able to reproduce the reasoning from retained evidence without relying on the author's memory.</p></div>`},

  {phase:"Pilot conclusion",title:"Recommend the campus assurance operating model",short:"Handover",body:`
    <p class="lead">Conclude what Catalyst Center assurance adds to the traditional campus and what must be corrected before production adoption.</p>
    <article class="stakeholder-record"><div class="record-type">Management review request</div><dl><dt>From</dt><dd>Trần Đức Long, CTO</dd><dt>To</dt><dd>SDN Network Architect</dd><dt>CC</dt><dd>CIO; Campus Operations; CISO</dd><dt>Subject</dt><dd>Assurance pilot decision package</dd></dl><p>Dear SDN Network Architect, good afternoon.</p><p>Thank you for completing the wired and wireless exploration. Management now needs a recommendation that separates immediate operational value from future architecture decisions.</p><p>Please identify the data-readiness gaps, workflows that reduced troubleshooting time, limitations that still require device or application evidence, and controls required before broader rollout. SDA remains outside this decision.</p><p class="record-signature">Regards,<br>Trần Đức Long<br>Chief Technology Officer<br>PetroVale Energy</p></article>
    <section class="evidence-pack"><h3>Submission checklist</h3><label><input type="checkbox" data-evidence="scope"> Release, RBAC, sites, time zone, and sample-data scope</label><br><label><input type="checkbox" data-evidence="baseline"> Wired, wireless, network-device, and issue baselines</label><br><label><input type="checkbox" data-evidence="wired"> Wired Device 360, Client 360, and Path Trace evidence</label><br><label><input type="checkbox" data-evidence="wireless"> WLC/AP/Client 360, RF, roaming, and onboarding evidence</label><br><label><input type="checkbox" data-evidence="incidents"> Incident triage, restoration, and RCA</label><br><label><input type="checkbox" data-evidence="operating"> Dashboard, alert, escalation, and runbook design</label></section>
    <h3>Recommendation structure</h3><ol><li>Operational outcomes proven by the sample data</li><li>Visibility and telemetry gaps</li><li>RBAC, retention, integration, and ownership requirements</li><li>Phased assurance rollout by site</li><li>Explicit statement that SDA is not part of this pilot</li></ol>
    <textarea data-field="recommendation" style="width:100%;min-height:180px" placeholder="Write the final recommendation"></textarea>
    <section class="references"><h3>Official references</h3><p><a href="https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/catalyst-center-assurance/3-1-x/b_cisco_catalyst_assurance_3_1_x_ug/b_cisco_catalyst_assurance_2_3_6_ug_chapter_0111.html" target="_blank" rel="noreferrer">Client Health and Client 360</a> · <a href="https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/catalyst-center-assurance/2-3-7/b_cisco_catalyst_assurance_2_3_7_ug/b_cisco_dna_assurance_2_3_6_ug_chapter_011.html" target="_blank" rel="noreferrer">Assurance Readiness</a> · <a href="https://www.cisco.com/c/en/us/support/docs/wireless/catalyst-9800-series-wireless-controllers/226132-troubleshoot-wireless-issues-with.html" target="_blank" rel="noreferrer">Wireless Troubleshooting with Catalyst Center</a></p></section>`}
];

const storageKey="petrovale-campus-assurance-lab-v1";const saved=JSON.parse(localStorage.getItem(storageKey)||"{}");const state={index:Math.min(Number(saved.index)||0,tasks.length-1),completed:new Set(saved.completed||[]),fields:saved.fields||{},evidence:saved.evidence||{}};const nav=document.getElementById("taskNav"),content=document.getElementById("taskContent"),title=document.getElementById("taskTitle"),phase=document.getElementById("phaseLabel"),previous=document.getElementById("previousButton"),next=document.getElementById("nextButton"),complete=document.getElementById("completeButton");function save(){localStorage.setItem(storageKey,JSON.stringify({index:state.index,completed:[...state.completed],fields:state.fields,evidence:state.evidence}))}function bind(){content.querySelectorAll("[data-field]").forEach(e=>{const k=e.dataset.field;if(state.fields[k]!==undefined)e.value=state.fields[k];e.addEventListener("change",()=>{state.fields[k]=e.value;save()})});content.querySelectorAll("[data-evidence]").forEach(e=>{const k=e.dataset.evidence;e.checked=Boolean(state.evidence[k]);e.addEventListener("change",()=>{state.evidence[k]=e.checked;save()})})}function renderNav(){nav.innerHTML=tasks.map((t,i)=>`<button class="task-link ${i===state.index?"active":""} ${state.completed.has(i)?"done":""}" data-index="${i}"><span>${state.completed.has(i)?"✓":i+1}</span><em>${t.short}</em></button>`).join("");nav.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{state.index=Number(b.dataset.index);render()}));document.getElementById("progressCount").textContent=`${state.completed.size} of ${tasks.length}`;document.getElementById("progressBar").style.width=`${state.completed.size/tasks.length*100}%`}function render(){const t=tasks[state.index];title.textContent=t.title;phase.textContent=t.phase;content.innerHTML=t.body;previous.disabled=state.index===0;next.disabled=state.index===tasks.length-1;complete.textContent=state.completed.has(state.index)?"Completed":"Mark complete";complete.classList.toggle("is-complete",state.completed.has(state.index));bind();renderNav();document.querySelector(".workspace").scrollTop=0;save()}previous.addEventListener("click",()=>{if(state.index>0){state.index--;render()}});next.addEventListener("click",()=>{if(state.index<tasks.length-1){state.index++;render()}});complete.addEventListener("click",()=>{state.completed.has(state.index)?state.completed.delete(state.index):state.completed.add(state.index);render()});document.getElementById("printButton").addEventListener("click",()=>window.print());render();
